tap 'homebrew/cask'
tap 'homebrew/bundle'
tap 'homebrew/cask-fonts'
tap 'homebrew/core'
tap 'neovim/neovim'

cask 'docker'
cask 'slack'
cask 'google-chrome'
cask 'firefox'
cask 'font-fira-code-nerd-font'
cask 'qlmarkdown'
cask 'vlc'
cask 'bettertouchtool'
cask 'alfred'
cask '1password'
cask 'spotify'
cask 'alacritty', args: {"no-quarantine": true}

brew 'bat'
brew 'lsd'
brew 'bpytop'
brew 'ctags'
brew 'diff-so-fancy'
brew 'fasd'
brew 'fd'
brew 'fzf'
brew 'imagemagick'
brew 'jp2a' 
brew 'lazygit'
brew 'neovim'
brew 'nvim', args: ['HEAD']
brew 'nvm'
brew 'python3'
brew 'rg'
brew 'ripgrep'
brew 'ruby'
brew 'shellcheck'
brew 'shfmt'
brew 'vim'
brew 'youtube-dl'
brew 'zsh'
