tap 'homebrew/cask'
tap 'homebrew/bundle'
tap 'homebrew/cask-fonts'
tap 'homebrew/core'
tap 'neovim/neovim'

cask 'google-chrome'
cask 'firefox'
cask 'font-fira-code'
cask 'iterm2'
cask 'qlmarkdown'
cask 'vlc'
cask 'bettertouchtool'
cask 'alfred'
cask '1password'

brew 'fzf'
brew 'neovim'
brew 'python3'
brew 'unrar'
brew 'zsh'
brew 'ripgrep'
brew 'fasd'
