"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$fill\
$git_branch\
$git_status\
$cmd_duration\
$time\
\n$character"""

[fill]
symbol = ' '
style = 'fg:240'

[directory]
style = 'fg:#729CD5'
format = '[$path]($style) '
truncate_to_repo = false
truncation_length = 100
truncation_symbol = '…/'
home_symbol = '~'

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
"Code" = "󰲋 "

[git_branch]
symbol = ''
style = 'fg:#abb2bf'
format = '[$symbol$branch]($style) '

[git_status]
style = 'fg:#db4b4b'
format = '[$all_status$ahead_behind]($style) '
conflicted = '≠'
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
up_to_date = '✓'
untracked = '?'
stashed = '\$'
modified = '!'
staged = '+'
renamed = '»'
deleted = '✘'

[cmd_duration]
disabled = false
style = 'fg:#494d64'
format = '[$duration]($style) '
min_time = 2000
show_milliseconds = false

[time]
disabled = false
style = 'fg:#494d64'
format = '[$time]($style) '
time_format = '%H:%M:%S'

[character]
success_symbol = '[❯](fg:#729CD5)'
error_symbol = '[❯](fg:#db4b4b)'
vimcmd_symbol = '[❮](fg:#729CD5)'
vimcmd_replace_one_symbol = '[❮](fg:#c678dd)'
vimcmd_replace_symbol = '[❮](fg:#c678dd)'
vimcmd_visual_symbol = '[❮](fg:#e0af68)'

[line_break]
disabled = false
