"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭─](fg:245) \
$directory\
$fill\
$git_branch\
$git_status\
$cmd_duration\
$time\
\n[╰─](fg:245) $character"""

[fill]
symbol = ' '
style = 'fg:240'

[directory]
style = 'fg:39'
format = '[ $path ]($style)'
truncation_length = 0
truncation_symbol = '…/'
home_symbol = '~'

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
"Code" = "󰲋 "

[git_branch]
symbol = ' '
style = 'fg:37'
format = '[$symbol$branch]($style) '

[git_status]
style = 'fg:196'
format = '[$all_status$ahead_behind]($style) '
conflicted = '≠'
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
up_to_date = '✓'
untracked = '?'
stashed = '$'
modified = '!'
staged = '+'
renamed = '»'
deleted = '✘'

[cmd_duration]
disabled = false
style = 'fg:240'
format = '[$duration]($style) '
min_time = 2000
show_milliseconds = false

[time]
disabled = false
style = 'fg:37'
format = '[$time]($style) '
time_format = '%H:%M:%S'

[character]
success_symbol = '[❯](fg:39)'
error_symbol = '[❯](fg:196)'
vimcmd_symbol = '[❮](fg:39)'
vimcmd_replace_one_symbol = '[❮](fg:purple)'
vimcmd_replace_symbol = '[❮](fg:purple)'
vimcmd_visual_symbol = '[❮](fg:yellow)'

[line_break]
disabled = false
