#!/bin/bash

# Sketchybar main config
# Inspired by linkarzu/dotfiles-latest, adapted for AeroSpace

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

# Font - same as kitty/nvim
FONT="SauceCodePro Nerd Font"
PADDINGS=2

# Bar appearance
bar=(
  height=40
  color=$BAR_COLOR
  border_width=1
  border_color=$BAR_BORDER_COLOR
  shadow=off
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  y_offset=0
  margin=0
  topmost=on
  blur_radius=20
)

sketchybar --bar "${bar[@]}"

# Defaults
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=26
  background.corner_radius=9
  background.border_width=2
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  scroll_texts=on
)

sketchybar --default "${defaults[@]}"

###############################################################################
# Left side
###############################################################################

# AeroSpace workspaces
WORKSPACES="A B D F G M O P Q R S T U V X Y Z"
for ws in $WORKSPACES; do
  sketchybar --add item space.$ws left \
    --set space.$ws \
    icon=$ws \
    icon.font="$FONT:Bold:16.0" \
    icon.color=$INACTIVE_COLOR \
    label.drawing=off \
    padding_left=3 \
    padding_right=3 \
    script="$PLUGIN_DIR/aerospace.sh" \
    --subscribe space.$ws aerospace_workspace_change
done

# Current app
source "$ITEM_DIR/front_app.sh"

###############################################################################
# Right side
###############################################################################

# Clock
source "$ITEM_DIR/clock.sh"

# Battery
source "$ITEM_DIR/battery.sh"

# Volume
source "$ITEM_DIR/volume.sh"

# CPU
source "$ITEM_DIR/cpu.sh"

###############################################################################

sketchybar --hotload on
sketchybar --update

echo "sketchybar configuration loaded.."
